export const FETCH_CLUBS_REQUEST = 'FETCH_CLUBS_REQUEST';
export const FETCH_CLUBS_SUCCESS = 'FETCH_CLUBS_SUCCESS';
export const FETCH_CLUBS_FAILURE = 'FETCH_CLUBS_FAILURE';
export const SET_CLUB = 'SET_CLUB';
