const SET_SELECTOR_STUDENTS = 'SET_SELECTOR_STUDENTS';
const FETCH_TIMESHEET_REQUEST = 'FETCH_TIMESHEET_REQUEST';
const FETCH_IN_TIMESHEET_SUCCESS = 'FETCH_IN_TIMESHEET_SUCCESS';
const FETCH_IN_TIMESHEET_FAILURE = 'FETCH_IN_TIMESHEET_FAILURE';
const FETCH_OUT_TIMESHEET_SUCCESS = 'FETCH_OUT_TIMESHEET_SUCCESS';
const FETCH_OUT_TIMESHEET_FAILURE = 'FETCH_OUT_TIMESHEET_FAILURE';
