export const FETCH_TIMESHEETS_REQUEST = 'FETCH_TIMESHEETS_REQUEST';
export const FETCH_TIMESHEETS_SUCCESS = 'FETCH_TIMESHEETS_SUCCESS';
export const FETCH_TIMESHEETS_FAILURE = 'FETCH_TIMESHEETS_FAILURE';

export const SET_TIMESHEET = 'SET_TIMESHEET';
